# Generated by Django 2.2 on 2019-06-02 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190602_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 20, 23, 14, 735964, tzinfo=utc)),
        ),
    ]
